### ISSUE TITLE
Enabler: Implement backstop.js for testing

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#14]
Implement [backstop.js](https://github.com/garris/BackstopJS) for testing.

## Sub-tasks
- [ ] Install backstop.js
- [ ] Get screenshots working in Docker
- [ ] Create initial tests
