### ISSUE TITLE
Implement SEO

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/gatsby-pcp#2]
Implement search engine optimization components within Gatsby. 

## Sub-Tasks
- [ ] Implement SEO component, deriving the metadata from the [site config](https://github.com/NCIOCPL/gatsby-pcp/blob/develop/gatsby-config.js)
- [ ] Add meta tags to the layout from #1
- [ ] Implement the sitemap plugin (installed but not configured)

## Notes

* [Gatsby SEO component documentation](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/)
* [Gatsby sitemap plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/)
