### ISSUE TITLE
Add Search to site

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#46]
Add search to the top right corner of the site. 

**AC for MVP:**

- Only PCP website search results
- Generates Results
- Basic search layout that loosely mimics [cancer.gov/search/results](https://www.cancer.gov/search/results?swKeyword=test)

**Sub-Tasks**
 

- [x] Add search link or search box to the main page. If search box, it would redirect to the search page with a query string.
- [x]  Implement search results page
- [x] Search results display
- [x] Number of results
- [x] Pagination
- [ ] Do we need environment variables? https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/

**Notes**
Mural Mockups - https://app.mural.co/t/worklifepage1864/m/worklifepage1864/1665585689544/22bc12c75257b9a87d068eb03dbda96d4f61d72e?sender=u391897c2e974e80931994272

**Screenshots:**

_Homepage_

![Image](https://user-images.githubusercontent.com/80473282/229586610-826d264e-42f1-42a8-9012-f34d818b4352.png)

Search Results page

![Image](https://user-images.githubusercontent.com/80473282/229586634-8a08bcb3-f31a-4db9-9502-7a1aec1af06e.png)
