### ISSUE TITLE
Homepage and Search - UX/IA Feedback

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/gatsby-pcp#65]
Apply IA and Design feedback:

## Subtasks

- [ ]  Left Allign Main nav
- [ ] Right Align Search funtion
- [ ] Adjust feature card sizing to be 401x357
- [ ] Replace banner image with blank image box
- [ ] Remove third level menu from Main Nav
        - these should only be viewable/accessible via left nav only

## Screenshots

![Image](https://user-images.githubusercontent.com/80473282/235738587-f6679d3e-d8c6-41e1-bab9-bacac1f30e32.png)

**Comment by erikscottmeyer** [comment]
I made a few other basic adjustments:
1.  Modified searchbox slightly to make magnifiying glass sizing even
2. Fixed hover color for magnifying glass in search bar
3. Changed topnav to wrap searchbar in blue container on mobile (nav and searchbar centered on mobile, nav right and searchbar left on table +)
4. Fixed site title so that always displays (logo disappears on mobile)
5. Put everything in large container (1350px)
6. Added sizing constraints for pictures on Members (to keep mobile pictures from being too large)
7. Put a max-width of 401px on feature card images (this addresses the image sizing concern referenced above)
